#!/usr/bin/env bash

# preprocess.sh will call preprocess/data_to_json.sh to download data (preprocess/get_data.sh) and convert to .json format
# 1. ./data_to_json.sh will
#   1) call get_data.sh to download the data
#   2) call get_file_dirs.py, get_hashes.py, group_by_writer.py, match_hashes.py to create .pkl and store them to intermediate
if [ ! -d "data/all_data_raw" ] || [ ! "$(ls -A data/all_data_raw)" ]; then
    cd preprocess
    echo "./data_to_json.sh"
    ./data_to_json.sh
    cd ..
fi

NAME="femnist" # name of the dataset, equivalent to directory name
## cnn features generated by vgg16
#if [ ! -d "data/all_data" ]|| [ ! "$(ls -A data/all_data)" ]; then
#  echo "python3 vgg16_zero.py"
#  python3 vgg16_zero.py
#fi
echo "python3 vgg16_zero.py"
python3 vgg16_zero.py


cd ../utils
echo "get train and test set"
rm -rf "data/train"
./preprocess.sh --name $NAME $@
cd ../$NAME